apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mykinds.example.com
  annotations:
    burrito.dev/layer: infrastructure
spec:
  group: example.com
  names:
    plural: mykinds
    singular: mykind
    kind: MyKind
    shortNames:
      - mk
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              message:
                type: string
    subresources:
      status: {}

